### ISSUE TITLE
Browser scrollbar disappearing under expandable review panel

### ISSUE THREAD

**Issue by matkun** [advanced-cms/advanced-reviews#107]
The handle part of the vertical scroll bar disappears behind the collapsed review panel when it gets too small on long pages. The image below shows it sticking out behind the panel on a medium length page.

![image (1)](https://user-images.githubusercontent.com/559763/73838449-fded7e80-4813-11ea-8c15-8614205d3034.png)

Expanding the review panel hides the scroll bar alltogether.

![image (2)](https://user-images.githubusercontent.com/559763/73838450-fe861500-4813-11ea-9510-08dceee7aaef.png)

We have very long articles at our current client's website, and while it is possible to scroll the page in other ways, editors has expressed a need for using the bar to scroll.

Would it be possible to change the review panel's offset slightly to the left to show the bar? or add the possibility to easily inject custom css or javascript to the page?

**Comment by barteksekula** [comment]
@matkun could you please test this out? https://github.com/advanced-cms/advanced-reviews/pull/108
I would really appreciate your help.

**Comment by matkun** [comment]
Works great :) Thanks for the fast response!

I've tested and commented here https://github.com/advanced-cms/advanced-reviews/pull/108#issuecomment-584017289

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.5.3
