### ISSUE TITLE
Expired content in ContentArea is still visible in externalContentView

### ISSUE THREAD

**Issue by steel80** [advanced-cms/advanced-reviews#112]
An expired block in a ContentArea is still visible in externalContentView mode. Desired behavior would be that no expired material is shown in the draft that is sent to the reviewer.

The issue is confirmed in Alloy with EPiServer CMS version 11.14.2.

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.5.3
