### ISSUE TITLE
Error while saving Pin in external content review

### ISSUE THREAD

**Issue by Anish-Peethambaran** [advanced-cms/advanced-reviews#114]
I am getting the error "Request failed with status code 404" while adding pin in external review content. Attaching the screen shot of the error. I am using version 0.5.3. Any help on this please?
![Add pin error](https://user-images.githubusercontent.com/54981074/76530206-4e877580-646b-11ea-9538-284f4d16a3ab.JPG)

**Comment by gregwiechec** [comment]
We had to do some changes related with URL routing in latest release and probably that could be problem.
Could you provide more information about steps to reproduce or setup that you have (like multisite, languages, etc.)?

**Comment by barteksekula** [comment]
@Anish-Peethambaran do you have any custom ExternalReviewOptions? ref. https://github.com/advanced-cms/advanced-reviews/#examples

**Comment by Anish-Peethambaran** [comment]
@gregwiechec Not a multisite, language is English UK. This is happening only for Edit links for external review. When the edit link is clicked and PIN is saved, error is shown.

**Comment by Anish-Peethambaran** [comment]
> @Anish-Peethambaran do you have any custom ExternalReviewOptions? ref. https://github.com/advanced-cms/advanced-reviews/#examples

This happens only in Edit link. I have enabled Edit link using the below code

 context.Services.Configure<ExternalReviewOptions>(options =>
            {
                options.EditableLinksEnabled = true;
            });

**Comment by barteksekula** [comment]
Are you able to reproduce the issue in the attached Alloy instance?
Just git clone this repo and run 'setup.cmd' and then 'site.cmd'

**Comment by barteksekula** [comment]
And did it work in 0.5.2 for you?

**Comment by Anish-Peethambaran** [comment]
@barteksekula I am using this add-on for first time with version 0.5.3.
I didn't try to reproduce in the Alloy instance, will try it if no other option. The issue here is, save PIN works for view link but not for edit links.

**Comment by barteksekula** [comment]
OK, I think I see the problem. 
Your url has a trailing slash '/' for some reason and this causes our routing table to go crazy.

Could you please check if there is a trailing slash when you copy the url from the widget?
![image](https://user-images.githubusercontent.com/1321664/76658306-1f106000-6574-11ea-9707-6f98be7c4d24.png)

**Comment by Anish-Peethambaran** [comment]
@barteksekula Thanks. You were right. There was a rule to add trailing slash to URL, this was causing the issue. Thanks for your support, really appreciate.

**Comment by Anish-Peethambaran** [comment]
Now showing error while trying to remove a PIN. Attaching the screen shot.
![image](https://user-images.githubusercontent.com/54981074/76756138-13dc5080-677d-11ea-96c3-ced2d8df14b7.png)

**Comment by barteksekula** [comment]
Both issues will be fix in the 0.5.4 release that will be available tomorrow.
https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.5.4

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.5.4
