### ISSUE TITLE
Page not found error after submitting PIN for save external review login

### ISSUE THREAD

**Issue by Anish-Peethambaran** [advanced-cms/advanced-reviews#116]
I created an external content view with PIN. Opened the link in new tab and submitted the saved PIN. But it showing page not found error. Attaching the screen shot and code used.

login url : 

https://localhost:44386/ExternalReviewLogin?id=71f40062-1254-42cf-9f5f-652bc225a12b

context.Services.Configure<ExternalReviewOptions>(options =>
            {
                options.EditableLinksEnabled = true;
                options.PinCodeSecurity.Enabled = true;
                options.PinCodeSecurity.CodeLength = 4;
            });

![image](https://user-images.githubusercontent.com/54981074/76783080-22406180-67a9-11ea-952a-8b1a2bd25d4e.png)

**Comment by gregwiechec** [comment]
Hi,
I was not able to reproduce it. If you clone the project and run, are you able to reproduce it?

**Comment by gregwiechec** [comment]
When you are testing it, you are already logged in to edit mode?

**Comment by Anish-Peethambaran** [comment]
yes, that's correct. Does that cause any issue?

**Comment by Anish-Peethambaran** [comment]
@gregwiechec @barteksekula I had gone through the code. After entering the security PIN, the action call for "/ExternalReviewLogin/Submit" is failing and CMS showing page not found. Any help on this?

**Comment by gregwiechec** [comment]
What do you mean by failing? Do you know what exception is thrown and is there a callstack?

**Comment by Anish-Peethambaran** [comment]
It is not throwing any exception. But after entering the PIN, Page not found is shown, 404 error.

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.5.4
