### ISSUE TITLE
For anonymous user contents are not fully loaded  in external Content View.

### ISSUE THREAD

**Issue by Anish-Peethambaran** [advanced-cms/advanced-reviews#120]
For anonymous users, contents are not loaded fully in external Content View. Only after logging-in  full contents are loaded. Is there any restrictions that only authenticated users will be able to see the full version of the page? Our requirement is to share the unpublished version of the page to external users who don't have a user account in CMS for review. Please share your comments on this.

**Comment by barteksekula** [comment]
@Anish-Peethambaran could you please write more? Your assumption is correct. What exactly is missing for an unauthenticated user?

**Comment by Anish-Peethambaran** [comment]
@barteksekula mega menu and heading content are missing. We are using hero banner block for heading content and menu item block for mega menu. These two are the main components that are missing for unauthenticated users. If we are logged-in then the page is fully loaded as expected. Do you think any permission or access issue might be the reason. Please let me know if you need more info on this

**Comment by barteksekula** [comment]
Just to double check, that mega menu and hero banner block are correctly displayed once you publish that page and then try to view it as an unauthenticated user in an incognito tab?

**Comment by Anish-Peethambaran** [comment]
@barteksekula Thanks for the hint. The pages had some access restrictions that was causing the issue. Now it is working fine. Many thanks for the support.

**Comment by barteksekula** [comment]
great to hear
