### ISSUE TITLE
ExternalReviewers access rights

### ISSUE THREAD

**Issue by Anish-Peethambaran** [advanced-cms/advanced-reviews#121]
@barteksekula Could you please confirm whether ExternalReviewers role should have admin privileges to edit and add review comments? Basically we dont want ExternalReviewers users to have edit access to CMS. They should be able to only edit/add review comments. Is this possible?

**Comment by barteksekula** [comment]
ExternalReviewers group does not need any kind of admin/edit priviledges or access to any content.
The default nuget install should set it all up for you:
https://github.com/advanced-cms/advanced-reviews/blob/master/src/alloy/web.config.transform#L17

By default the members of ExternalReviewers will not be able to login in to both Edit & Admin mode.
