### ISSUE TITLE
How to differentiate between internal and public URL in live site for Links

### ISSUE THREAD

**Issue by Anish-Peethambaran** [advanced-cms/advanced-reviews#122]
For live site, we have two URL's , public and internal URL, something like test.com and test.prod.dxcloud.episerver.net. When we create view/edit links, links will be generated based on the current URL or do we need to add any settings for this?

Say for example, when I create a view link in internal site, test.prod.dxcloud.episerver.net, whether it will create externalContentView with test.prod.dxcloud.episerver.net or test.com ?

**Comment by barteksekula** [comment]
I think the links are relative, so the host is not included.
so, both 
https://public.site.com/externalView....
and
https://internal.site.com/externalView....
should work

is this ok? if not then it will be easy for you to do redirects in the webserver

**Comment by Anish-Peethambaran** [comment]
Okay. One more query. Is it possible to force the user to give a PIN while creating external content view when PIN security is enabled? Now, first we need to create the View link, then edit the link and add PIN. Basically we want to restrict the user from sharing the link via email without creating a PIN. Is this possible?

**Comment by barteksekula** [comment]
So you would like the PIN input to appear while creating the link, correct?

**Comment by Anish-Peethambaran** [comment]
Yes, so that user is reminded to enter PIN. Currently the user can create the link and share via email without a PIN. It would be a good feature to have a property to indicate if its a mandatory field or optional.

**Comment by barteksekula** [comment]
I agree, it makes sense.

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.5.6

**Comment by barteksekula** [comment]
You will now have the option to require a PIN before adding a new link.
https://github.com/advanced-cms/advanced-reviews#pincodesecurityoptions
