### ISSUE TITLE
Unpublished block is not display in review when used contentArea.FilteredItems in ContentAreaRenderer

### ISSUE THREAD

**Issue by nguyenminhvuong** [advanced-cms/advanced-reviews#136]
I created a class named BootstrapAwareContentAreaRenderer inherited from **ContentAreaRenderer**. In this class, I override two methods:

```
public override void Render(HtmlHelper htmlHelper, ContentArea contentArea)
{
	//other logic here

	RenderContentAreaItems(htmlHelper, contentArea.FilteredItems);
	
	//other logic here
}

protected override void RenderContentAreaItems(HtmlHelper htmlHelper, IEnumerable<ContentAreaItem> contentAreaItems)
{
	//display logic here
}
```

I found the root cause is contentArea.FilteredItems. Because of **FilteredItems** does not include unpublished blocks.

My workaround is using **ExternalReview.IsInExternalReviewContext** to check the page is in review mode or not.

`RenderContentAreaItems(htmlHelper, ExternalReview.IsInExternalReviewContext ? contentArea.Items : contentArea.FilteredItems);`

**Comment by Mordrag** [comment]
Just stumbled upon the same issue. We are using the FilteredItems a lot in our project and changing the code as suggested above is not an option for us.

For me it looks like the IPublishedStateAssessor is the culprit here. I created a simple decorator around the default service which seems to help. Maybe you can have a deeper look:

```
public class PublishedStateAssessorDecorator : IPublishedStateAssessor
{
	private readonly IPublishedStateAssessor _defaultService;

	public PublishedStateAssessorDecorator(IPublishedStateAssessor defaultService)
	{
		_defaultService = defaultService;
	}

	public bool IsPublished(IContent content, PublishedStateCondition condition)
	{
		if (ExternalReview.IsInExternalReviewContext && ExternalReview.CustomLoaded.Contains(content.ContentLink.ToString()))
		{
			IContent cachedContent = ExternalReview.GetCachedContent(ServiceLocator.Current.GetInstance<LanguageResolver>().GetPreferredCulture(), content.ContentLink);
			if (cachedContent != null)
			{
				return true;
			}
		}
		return _defaultService.IsPublished(content, condition);
	}
}

```

**Comment by barteksekula** [comment]
Guys, what is the reason you are rendering content area items yourself rather than using PropertyFor?
https://github.com/episerver/alloy-mvc-template/blob/master/src/Alloy.Mvc.Template/Views/StartPage/Index.cshtml#L4

**Comment by barteksekula** [comment]
@benklaw just wanted to make sure - you are not using a custom renderer right?
@nguyenminhvuong your workaround that you mentioned - you did apply that only once in your custom BootstrapAwareContentAreaRenderer right?

**Comment by barteksekula** [comment]
anyway @benklaw your solution works great, would you like to contribute a PR?

**Comment by nguyenminhvuong** [comment]
@barteksekula: yeah, I applied it in one place. 

I use PropertyFor in view layer too, I also use FilterItem because of personalized purposes.

**Comment by barteksekula** [comment]
Fixed in https://github.com/advanced-cms/advanced-reviews/pull/144
