### ISSUE TITLE
External Links wont load in incognito mode

### ISSUE THREAD

**Issue by Jptc97** [advanced-cms/advanced-reviews#137]
After install the Nuget package, I generated a external link to test if it works in incognito mode but it wouldn't load the images and some parts of the footer. I have not implemented any of the options class or any of that. Is that the reason why its not loading?

**Comment by barteksekula** [comment]
@Jptc97 does it work for you on a clean Alloy site? we would need some more info what's missing i.e. if the images are on the same domain, how they are included on the page (ContentArea? Url?), what is in your footer?

**Comment by Jptc97** [comment]
@barteksekula Hey, I figured it out... I had to add roles to the page to allow who can read the page. After adding that role it worked for me. Thank you
