### ISSUE TITLE
Testing code apparently left behind causing URLs to be generated without trailing slash

### ISSUE THREAD

**Issue by xecrets** [advanced-cms/advanced-reviews#138]
Commit https://github.com/advanced-cms/advanced-reviews/commit/c555f4d153e8749aa9abba9ac4c85f43ae9a9dae causes changed behavior, and from the commit-comment it seems to be code that is "just for testing". In any case, it should not set RoutingOptions.UseTrailingSlash to any value, but let the consumer decide.

**Comment by barteksekula** [comment]
fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.7.1
