### ISSUE TITLE
Incorrect ExternalReview link in case the original link contains query parameters

### ISSUE THREAD

**Issue by pavel-klevtsov** [advanced-cms/advanced-reviews#143]
Hi.

Let's say we have an Url property like this:
![url_edit](https://user-images.githubusercontent.com/67944494/89760397-f70e3400-daf4-11ea-9c71-325af1da3bfa.png)
User-friendly link will be "_/service-message-page/?service=Retired_"
When we call for **@Url.ContentUrl(LinkUrl)** in ExternalReview mode, the result will be something like "_/service-message-page/?service=Retired/externalContentView/7ac4062b-306d-4d96-8dfc-223bf71e7370?preview_generated=true_"

This happens because of **UrlResolver.GetUrl(UrlBuilder urlBuilderWithInternalUrl, VirtualPathArguments arguments)** which is overridden in [PreviewUrlResolver](src/external-reviews/PreviewUrlResolver.cs).
The method calls for **_defaultUrlResolver.GetUrl(urlBuilderWithInternalUrl, arguments)** - the result is "_/service-message-page/?service=Retired_". Then the result is updated by **AppendGeneratedPostfix** that simply adds "_/externalContentView/[token guid]_" and the result is like _"/service-message-page/?service=Retired/externalContentView/7ac4062b-306d-4d96-8dfc-223bf71e7370?preview_generated=true_".

I'd expect here moving all parameters after "_preview_generated_" param.

A less obvious problem exists in another place.
If for some reason **UrlResolver.GetUrl** for the home page returns an URL with parameters in normal mode, then External review widget will generate incorrect URL in the same way as described above.
It happens because of **ExternalReviewStore.Post** -> **ExternalReviewLinksRepository.AddLink** -> **ExternalReviewLinkBuilder.FromExternalReview** calling.
As we can see in [ExternalReviewLinkBuilder.FromExternalReview](src/external-reviews/ReviewLinksRepository/ExternalReviewLinkBuilder.cs):

var url = _startPageUrlResolver.GetUrl(externalReviewLinkDds.ContentLink); // (urlResolver.GetUrl under the hood) Let's say it is _site.com/innerUrl/?param=value_

externalUrlPrefix = UrlPath.Combine(url, _options.ContentPreviewUrl); // _site.com/innerUrl/?param=value/externalContentView_

LinkUrl = UrlPath.Combine(externalUrlPrefix, externalReviewLinkDds.Token), // _site.com/innerUrl/?param=value/externalContentView/7ac4062b-306d-4d96-8dfc-223bf71e7370`_

So the "load the URL string and the externalContentView substrings to it without checking for query params" logic exists at least in two different places. Maybe there are more.

**Comment by barteksekula** [comment]
@pavel-klevtsov Could you please add a bit more code, just to make sure I understand.
I've tried to reproduce it in the same site but I failed.

Please include:
1. Model property
2. How do you render that property in your view

**Comment by barteksekula** [comment]
@pavel-klevtsov I would appreciate if you could test this out https://github.com/advanced-cms/advanced-reviews/pull/144

**Comment by pavel-klevtsov** [comment]
@barteksekula I can confirm it's working fine, thanks. It fixes first issue. Do you need more info about the second one?

**Comment by barteksekula** [comment]
Yes please

**Comment by pavel-klevtsov** [comment]
@barteksekula 
Let's say we have a special "error page" that we use to show any error messages like "Page not found", "Under construction" and so on. Exact message is regulated by query param like _/service-page/?service=Asset_Update_
Let's say we have a home page configured in CMS but we do not want to show it. Instead we want to show the error page with a query param "_?service=Asset_Update_".
We want to use Shortcut page property. We cannot use "Shortcut to another content item" Shortcut type because it does not allow to provide a query param. Instead we use Shortcut to page on another website param and set External Link to something like "_/link/0b741d53a7574b5c98ca02294e31db95.aspx?service=Asset_Update_" - in fact it is not external link, it is the real internal link to the error page.
After that, if we open home page's URL, we will see "_/service-page/?service=Asset_Update_" instead.

For now it's working. Maybe it is not intuitive to use External link here, but let's say the decision was made to do it in this way.

Now we want to generate External Review link. We click "View" in External Review links widget and the generated link is like "_[site.com]/link/0b741d53a7574b5c98ca02294e31db95.aspx?service=Asset_Update/externalContentView/9eeddd8c-4531-454b-8d79-6892db099de7_"

**Comment by barteksekula** [comment]
Can you please share the code?
I mean property type and how it's rendered in the view.
So just to make it clear, why do you need that property for the external review process?

**Comment by pavel-klevtsov** [comment]
It is all about CMS editing. So there is no view and to rendering.
![image](https://user-images.githubusercontent.com/67944494/89907136-f0ff7c80-dbf4-11ea-88ae-2b5ce3acd85e.png)
![image](https://user-images.githubusercontent.com/67944494/89907490-6bc89780-dbf5-11ea-95d5-cced31f77480.png)
![image](https://user-images.githubusercontent.com/67944494/89907847-d974c380-dbf5-11ea-8a28-2fa276093b30.png)
So if we fill Shortcut in this way and create new External View link, this link will be like on last screenshot (at the bottom)

**Comment by barteksekula** [comment]
It seems to me that it should not be possible to create an External Link if the current page is a shortcut correct?

**Comment by barteksekula** [comment]
Sorry but I don't get it. I added a page which is a shortcut to another website with query string param.
![image](https://user-images.githubusercontent.com/1321664/89949053-8a478680-dc27-11ea-8014-1e667b5f5e15.png)
And the url resolves correctly:
http://localhost:8080/en/externalContentView/46def7f1-2134-42ce-886b-957affcd905d
resolves to the shortcut url I used.

**Comment by barteksekula** [comment]
If you really need a fix for that then probably the best and fastest way would be for you to fork this repo and add a reproducible scenario, that would be a huge help :)

**Comment by barteksekula** [comment]
The issue with UrlResolver was fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.7.3
Please add a new issue for the shortcut, ideally with a reproducible code. Thanks
