### ISSUE TITLE
Incorrect link in External review links widget for Home page shortcutting the link with query string

### ISSUE THREAD

**Issue by pavel-klevtsov** [advanced-cms/advanced-reviews#145]
Since the issue happens in CMS mode, there is no possible reproducible code, I think.
Steps to reproduce:
1. Go to CMS mode (_site.com/episerver/cms_), 
2. open **Home page** settings (sorry, I forgor to mention before - the issue applies only to home page).
3. Set Shortcut setting. Shortcut type should be "Shortcut to page on another website" and External Link should contain something like "_/link/0b741d53a7574b5c98ca02294e31db95.aspx?service=Asset_Update_" (meaning containing a query param).
4. Go to External review links widget and generate a new link.
5. The link will be like "_/link/0b741d53a7574b5c98ca02294e31db95.aspx?service=Asset_Update/externalContentView/9eeddd8c-4531-454b-8d79-6892db099de7_".

**Comment by pavel-klevtsov** [comment]
Hi. Any progress on this?

Let me still provide some test code that does the same as the above steps.
This is not a working code, because the problem as I described above is happening in the CMS, but the result of this code is exactly the same.

public void Test_StartPage_ExternalReviewLink_For_ParameterizedShortcutting()
{
    var contentLoader = ServiceLocator.Current.GetInstance<IContentRepository>();
    var homePage = contentLoader.Get<HomePage>(ContentReference.StartPage);
    var homePageClone = homePage.CreateWritableClone();
    homePageClone.LinkType = PageShortcutType.External;
    homePageClone.LinkURL = @"/link/0b741d53a7574b5c98ca02294e31db95.aspx?service=Asset_Update";
    contentLoader.Save(homePageClone, AccessLevel.Publish);
    var externalReviewLinksRepository = ServiceLocator.Current.GetInstance<IExternalReviewLinksRepository>();
    var addLinkResults = externalReviewLinksRepository.AddLink(ContentReference.StartPage, false, TimeSpan.FromDays(5), null);
    var externalReviewUrl = addLinkResults.LinkUrl;
    //Expected: /link/0b741d53a7574b5c98ca02294e31db95.aspx/externalContentView/[GUID]?service=Asset_Update
    //Actual: /link/0b741d53a7574b5c98ca02294e31db95.aspx?service=Asset_Update/externalContentView/[GUID]
    var serviceParam = new UrlBuilder(externalReviewUrl).QueryCollection["service"];
    //Expected: "Asset_Update" 
    //Actual: "Asset_Update/externalContentView/[GUID]"
}
(sorry, "insert code" tags are not working here for some reason).

**Comment by gregwiechec** [comment]
Using a shortcut on StartPage is an edge case. It will be hard to solve in default implementation. But in next release it will be possible to use custom StartPageResolver:
https://github.com/advanced-cms/advanced-reviews/compare/bugfix/allow-to-override-startpageresolver?expand=1

Please check CustomStartPageResolver:
https://github.com/advanced-cms/advanced-reviews/pull/152/files#diff-b4e2e818e33ebacaefe6cc066508506a
it resolve link URL using SiteDefinition. Maybe it will help in your scenario.
Otherwise you need to provide your own custom implementation.

**Comment by pavel-klevtsov** [comment]
@gregwiechec 
I think using custom StartPageResolver does not help in this issue.
Let's take a look on a part of the code I provided.
...
_externalReviewLinksRepository.AddLink(ContentReference.StartPage, false, TimeSpan.FromDays(5), null)_
...

It calls for 

_ExternalReviewLinkBuilder.FromExternalReview(ExternalReviewLinkDds externalReviewLinkDds)_

method, which contains these lines:

_var url = startPageUrlResolver.GetUrl(externalReviewLinkDds.ContentLink);_

/* in our case it works perfectly. It returns "/link/0b741d53a7574b5c98ca02294e31db95.aspx?service=Asset_Update" as expected. No need to override used resolver. */

_externalUrlPrefix = UrlPath.Combine(url, options.ContentPreviewUrl);_
// Expected: /link/0b741d53a7574b5c98ca02294e31db95.aspx/externalContentView/?service=Asset_Update
// Actual: /link/0b741d53a7574b5c98ca02294e31db95.aspx?service=Asset_Update/externalContentView

...

LinkUrl = UrlPath.Combine(externalUrlPrefix, externalReviewLinkDds.Token) 
// Expected: /link/0b741d53a7574b5c98ca02294e31db95.aspx/externalContentView/[GUID]?service=Asset_Update
// Actual: /link/0b741d53a7574b5c98ca02294e31db95.aspx?service=Asset_Update/externalContentView/[GUID]

So I don't see how can I overrride StartPageResolver to avoid adding URL fragments after query params.

I think it make sense to replace Url.Combine(...) methods with UrlBuilder usage, as you already did 
in PreviewUrlResolver.cs here:
https://github.com/advanced-cms/advanced-reviews/pull/144/files#diff-dad5b69214bd7b43b9502dcbc6f03e03

**Comment by barteksekula** [comment]
@pavel-klevtsov makes sense, would you like to give it a shot?

**Comment by pavel-klevtsov** [comment]
You mean, to create a PR with the changes? Yeah, why not. Will do.

**Comment by barteksekula** [comment]
Great! 👍

**Comment by barteksekula** [comment]
@pavel-klevtsov any idea when you might be able to PR? I have some time today so please let me know about your plans.

**Comment by pavel-klevtsov** [comment]
@barteksekula 
I'm trying to push my branch, but what is what I have:
_Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/advanced-cms/advanced-reviews.git/': The requested URL returned error: 403
Pushing to https://github.com/advanced-cms/advanced-reviews.git_
Any ideas?

**Comment by barteksekula** [comment]
@pavel-klevtsov you will need to create a fork first and do a cross-repo PR.

**Comment by barteksekula** [comment]
Released in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.7.4

**Comment by pavel-klevtsov** [comment]
@barteksekula Great, thank you!
