### ISSUE TITLE
Scrollbar in context menu for review links widget in Firefox

### ISSUE THREAD

**Issue by linhdoan** [advanced-cms/advanced-reviews#146]
The JS logic for calculating context menu height is not working with EPiServer.CMS.UI latest version (11.28.0).
The issue happen because the "mdc-list-item" class in the new UI package has been changed from height 48px to 32px.

Step to reproduce:

1. Install EPiServer.CMS.UI version 11.28.0 & Advanced.CMS.AdvancedReviews version 0.7.3
2. Add the initialization class to enable Editable link.
3. Add the "External review links" widget to the end of right panel in Edit UI.
4. Click on add link button & notice the scrollbar on the context menu (Firefox display it very big & hide part of the context menu).

![image](https://user-images.githubusercontent.com/17606907/90852169-fef59000-e3a0-11ea-956d-6e88099efd05.png)

**Comment by barteksekula** [comment]
@linhdoan hi, I'm not able to reproduce this, it only happened to me after I zoomed in in my browser (to 130%).
![image](https://user-images.githubusercontent.com/1321664/92099495-dcb93480-edda-11ea-9813-8df2f908cc9a.png)
But on 100% it works fine in all browsers.

**Comment by barteksekula** [comment]
Released in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.7.4
