### ISSUE TITLE
Use screenshot attachment IE11

### ISSUE THREAD

**Issue by MorJonSkan** [advanced-cms/advanced-reviews#147]
You cant attach screenshot for IE 11
Should it be possible to hide the “Attach screenshot”-button?
![attach screenshot](https://user-images.githubusercontent.com/36155651/91276960-7ef56e80-e782-11ea-811e-68a6b96f0ca2.jpg)

**Comment by barteksekula** [comment]
@MorJonSkan Could you please test https://github.com/advanced-cms/advanced-reviews/tree/bugfix/allow-disabling-attachments

**Comment by MorJonSkan** [comment]
@barteksekula Confirmed OK, with the configuration set to false in init module
![image](https://user-images.githubusercontent.com/36155651/92241687-ed42db00-eebe-11ea-808b-c9f7b686e7b8.png)

**Comment by barteksekula** [comment]
Released in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.7.4
