### ISSUE TITLE
IE11 - CSS for checkboxes are not supported

### ISSUE THREAD

**Issue by MorJonSkan** [advanced-cms/advanced-reviews#148]
Icons in IE 11 is all the same.

![css-ie11](https://user-images.githubusercontent.com/36155651/91277117-af3d0d00-e782-11ea-8296-7e074d45130a.jpg)

**Comment by barteksekula** [comment]
Can you please check if it helps? https://github.com/advanced-cms/advanced-reviews/pull/151

**Comment by MorJonSkan** [comment]
@barteksekula Confirmed ok
![image](https://user-images.githubusercontent.com/36155651/92240852-8b35a600-eebd-11ea-9fc6-b89de4017abc.png)

**Comment by barteksekula** [comment]
Released in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.7.4
