### ISSUE TITLE
404 for External Review link for pages having changed “Name in URL” property

### ISSUE THREAD

**Issue by pavel-klevtsov** [advanced-cms/advanced-reviews#156]
There is issue about routing the external review link for the pages that have “Name in URL” property changing after last published version.

Let’s say we have site http://siteName.com/ and there is an page hierarchy inside like “page1” → “page2”. The user-friendly link for the bottom page will be http://siteName.com/page1/page2/. Let’s say we created drafts (no publishing) for both inner pages changing “Name in URL” properties to “page1-new”and “page2-new”. The link for published version will persist the same and it will still work.

The generated external review link will be like this:

http://siteName.com/page1-new/page2-new/externalContentView/15dd8ff0-5512-4323-bec0-a1a14ce19eb9?preview_generated=True

This link will not work. It will result in error 404.

**Comment by barteksekula** [comment]
@pavel-klevtsov Could you please share the steps to reproduce? Are you just generating the urls from the widget?
Because we changed that to always resolve to the start page and append the token to start page https://github.com/advanced-cms/advanced-reviews/commit/13b370937429c04169d18e8f58a666f980492b41
Do you use the project?

**Comment by pavel-klevtsov** [comment]
@barteksekula 
1. Create a page under Home page. Name it, let's say, "testPage". Publish it.
2. Add  PageReference-typed property to Home page, point it to "testPage" page, publish it.
3. Render the property using UrlResolver.GetUrl method. The result wll be like "/testPage/".
4. Open "testPage", change Name in URL to "testPageNew". Do not publish it.
5. Go in CMS to Home page, generate a new external review link, open it. The link will be like "/testPageNew/externalContentView/40fe85d2-573b-48c2-94af-15828ed52904?preview_generated=True". 
6. Try to open it.
7. 404

**Comment by barteksekula** [comment]
@pavel-klevtsov Do you have project selected?

**Comment by pavel-klevtsov** [comment]
@barteksekula Yes, the same project selected for both of pages. Can't reproduce the error?

**Comment by barteksekula** [comment]
@pavel-klevtsov I've just reproduced. It will be hard to fix unfortunately but I will think about it today.

**Comment by pavel-klevtsov** [comment]
@barteksekula 
Ok, looks like you fixed the scenario that I describer above. On the step 5 I see now the link "/testPage/externalContentView/40fe85d2-573b-48c2-94af-15828ed52904?preview_generated=True" and it is working fine.

Now let me describe another scenario.
1. Create a page under Home page. Name it, let's say, "testPage". Publish it.
2. Create another page under "testPage". Name it, let's say, "testSubPage". Publish it.
3. Add PageReference-typed property to Home page, point it to "testSubPage" page, publish it.
4. Render the property using UrlResolver.GetUrl method. The result wll be like "/testPage/testSubPage".
5. Open "testPage", change Name in URL to "testPageNew". Do not publish it.
6. Go in CMS to Home page, generate a new external review link, open it. The link will be like "/testPageNew/testSubPage/externalContentView/40fe85d2-573b-48c2-94af-15828ed52904?preview_generated=True".
7. Try to open it.
8. 404

So only the last fragment is set as expected.

Also please check both scenarios for the property that has type of Episerver.Url instead of PageReference. Use UrlExtensions.ContentUrl(this UrlHelper urlHelper, Url url) to get the link.  It ends in 404 for both scenarious.
