### ISSUE TITLE
How to use SiteDefinition.Hosts instead of SiteDefinition.Current.SiteUrl when send email

### ISSUE THREAD

**Issue by nguyenminhvuong** [advanced-cms/advanced-reviews#162]
Hi, 

This is not a product issue. I just want to find a solution to my personal issue.

When send an email with review link, the addon uses SiteDefinition.Current.SiteUrl as a primary domain. But I want to use another domain in SiteDefinition.Hosts. 

Is there anyway to do this?

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.7.5

**Comment by barteksekula** [comment]
@nguyenminhvuong were you able to upgrade to 0.7.5 to give it a try? there's an abstraction on top of SiteDefinition.Current.SiteUrl

**Comment by nguyenminhvuong** [comment]
@barteksekula thanks so much. It works for me
