### ISSUE TITLE
Review panel has been disappeared when left click to create new review entry

### ISSUE THREAD

**Issue by nguyenminhvuong** [advanced-cms/advanced-reviews#164]
The issue occured from version 0.7.3. It's ok in version 0.7.2

![Screenshot_1](https://user-images.githubusercontent.com/14576574/94120437-4d072300-fe7a-11ea-96da-e0836bedf9b3.png)

**Comment by barteksekula** [comment]
@nguyenminhvuong  what if you expand it using the chevron icon?

**Comment by nguyenminhvuong** [comment]
if I click on the chevron icon only, it expands the panel. When I try to create a new review, the panel disappears completely and no review form displayed.

I tested on the Alloy site with external review v 0.7.4

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.7.5
