### ISSUE TITLE
How to remove authentication in review edit mode

### ISSUE THREAD

**Issue by nguyenminhvuong** [advanced-cms/advanced-reviews#167]
Hi,

My customer wants to remove the authentication when open the edit link. I know it's not possible, but just want to find a solution for it.

Thanks

**Comment by barteksekula** [comment]
@nguyenminhvuong Sure it's possible. Just give all users the rights to `externalContentReviews` & `EPiServer/advanced-cms.ExternalReviews` locations like this:
```xml
  <location path="externalContentReviews">
    <system.web>
      <authorization>
        <allow users="*" />
      </authorization>
    </system.web>
  </location>
  <location path="EPiServer/advanced-cms.ExternalReviews">
    <system.web>
      <authorization>
        <allow users="*" />
      </authorization>
    </system.web>
  </location>
```

**Comment by barteksekula** [comment]
Please confirm if it works and close the ticket. I will add it to our FAQ.

**Comment by nguyenminhvuong** [comment]
Thanks @barteksekula 

I tested it in the Alloy site, it worked perfectly. But in my project, it returns 404. I'm investigating. 

Please close the ticket.

Thanks for your support
