### ISSUE TITLE
/externalContentReviews/AddPin 400 (Bad Request) Request failed with status code 400

### ISSUE THREAD

**Issue by harinarayanann** [advanced-cms/advanced-reviews#168]
Hi,
We are getting 400 error while trying to add pin, its happening only in the external review add pin.
![image](https://user-images.githubusercontent.com/46997692/95989335-c1b0fa00-0e47-11eb-9d9a-19df78b7f964.png)

![image](https://user-images.githubusercontent.com/46997692/95987031-819c4800-0e44-11eb-9986-4da89c467490.png)

Note: It's happening on my project only, Alloy project working fine.

please let us know if any workaround required.

Regards,
Hari

**Comment by harinarayanann** [comment]
Adding to the above, I'm not seeing "externalPageReview" in my project but I can see in the Alloy
MyProject:
![image](https://user-images.githubusercontent.com/46997692/95999591-a9df7300-0e53-11eb-84f0-0f3f272b1f0a.png)

Alloy:
![image](https://user-images.githubusercontent.com/46997692/95999504-92a08580-0e53-11eb-9464-39dbe450aedf.png)

**Comment by harinarayanann** [comment]
We came to know that it's happening due to Referrer-Policy we have in Web.config.

![image](https://user-images.githubusercontent.com/46997692/96408985-3302fb00-1202-11eb-8a8b-036d6fd18f95.png)

**Comment by harinarayanann** [comment]
Finally, I've updated the below code and it's working fine now.
![image](https://user-images.githubusercontent.com/46997692/96439507-63f42780-1224-11eb-8f4f-b11a77c90257.png)

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.7.6

**Comment by barteksekula** [comment]
We are no longer using referrer.
