### ISSUE TITLE
External link not picking up correct language

### ISSUE THREAD

**Issue by puneetdev** [advanced-cms/advanced-reviews#169]
If a content exists in multiple languages, while creating the external link for a content, the external link is picking up the primary language of the content, not the currently selected language. For example, if a content exists in 2 languages, de-ch and fr-ch and the primary language is fr-ch. Then, if we create the external review link for the content in de-ch, the link is showing the content from fr-ch.

**Comment by tkumbari** [comment]
@barteksekula @gregwiechec , Happy to hear feedback

**Comment by barteksekula** [comment]
@puneetdev are you able to reproduce on the sample alloy? I've just tried and it works fine for me.
Please provide steps to reproduce.

**Comment by barteksekula** [comment]
@puneetdev any response?

**Comment by barteksekula** [comment]
Closed due to inactivity.
