### ISSUE TITLE
Personalization through Vistorgroup is not considering in preview mode

### ISSUE THREAD

**Issue by harinarayanann** [advanced-cms/advanced-reviews#172]
Hi,
When we apply personalization using visitor groups, the preview/drafted page is not considering personalization and displaying all the blocks available in ContentArea.

Please let us know if any workaround.

Regards, 
Hari

**Comment by barteksekula** [comment]
Hi,
You are not the first one asking for VG support. There is no workaround as of now.
We will think about adding support for adding the ability to add the option to `View as user/role` option to tokens.

**Comment by harinarayanann** [comment]
Got it, thank you for the reply.

**Comment by barteksekula** [comment]
@harinarayanann would you expect to be able to associate a VG when creating an external review link?

**Comment by barteksekula** [comment]
It was already added in https://github.com/advanced-cms/advanced-reviews/pull/175
Will be release in v0.8.0 soon

**Comment by barteksekula** [comment]
The visitor groups has to be defined during creation of the review link. 
https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.8.0
