### ISSUE TITLE
View link and edit link has been removed automatically when updating page

### ISSUE THREAD

**Issue by nguyenminhvuong** [advanced-cms/advanced-reviews#173]
Hi,

I tested it on Alloy site with version 0.75 & 0.76. Here are reproduce steps:

1. Go to Editor mode
2. Edit published page or unpublished page
3. Add new external reviews link (view link or edit link)
4. Update something on the page
5. The external reviews link is disappear

**Comment by barteksekula** [comment]
the links are associated with a specific version. so one WorkID has many edit/view links. it is not possible to create a version agnostic token.

**Comment by barteksekula** [comment]
@nguyenminhvuong can we close the ticket? or there's something more you would like to bring up?

**Comment by nguyenminhvuong** [comment]
OK I got it. This is a new feature that I don't know. Please close a ticket
