### ISSUE TITLE
New feature request: view as a visitor group panel

### ISSUE THREAD

**Issue by nguyenminhvuong** [advanced-cms/advanced-reviews#176]
Hi,

My customer wants to have a panel like this when reviews a page:

![Screenshot_1](https://user-images.githubusercontent.com/14576574/98086422-5049f180-1eb1-11eb-9ea7-89e4b323c1d7.png)

Is it possible? Please consider

Many thanks

**Comment by barteksekula** [comment]
It was already added in https://github.com/advanced-cms/advanced-reviews/pull/175
Will be release in v0.8.0 soon

**Comment by barteksekula** [comment]
The visitor groups has to be defined during creation of the review link. But the functionality works as you would expect.
https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.8.0
