### ISSUE TITLE
SEO Toolbox is redirecting the drafted link also to actual page

### ISSUE THREAD

**Issue by harinarayanann** [advanced-cms/advanced-reviews#177]
Hi,
I was facing an issue that, the drafted review links are always redirecting to the actual page, after a day of research I came to know that our redirect manager ([https://seotoolbox.net/]) is redirecting to the actual page.  

**Suggested Fix in SEO Toolbox:**
To avoid that we have to add the below two URLs to the Ignored list.

![image](https://user-images.githubusercontent.com/46997692/98511808-54985500-228b-11eb-9601-c0e56877497a.png)

Regards,
Hari

**Comment by barteksekula** [comment]
What is the expected fix for your issue?

**Comment by harinarayanann** [comment]
> What is the expected fix for your issue?

I have highlighted above.

**Comment by barteksekula** [comment]
But what is this SEO Toolbox?

**Comment by harinarayanann** [comment]
> But what is this SEO Toolbox?

It's and Redirects manager (another plugin) we can get more details from here https://seotoolbox.net/. [](https://seotoolbox.net/)

**Comment by barteksekula** [comment]
And the bugfix is expected in our code or in their code?

**Comment by barteksekula** [comment]
Or maybe it's just something we could add to our README? Like, "if you have mogul seo toolbox then you might want to add this and that to ignored list". Would you like to contribute?

**Comment by harinarayanann** [comment]
> Or maybe it's just something we could add to our README? Like, "if you have mogul seo toolbox then you might want to add this and that to ignored list". Would you like to contribute?

Yes, That will be helpful. Sure I can,

**Comment by harinarayanann** [comment]
Hi @barteksekula , I'm trying to push the README update branch (bugfix/177), but looks like I don't have access, getting below error, can please provide access incase if that is the case.

`Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/advanced-cms/advanced-reviews.git/': The requested URL returned error: 403
Pushing to https://github.com/advanced-cms/advanced-reviews.git`

**Comment by barteksekula** [comment]
I think you should push to your fork first and then create a PR from your fork to this repo.

**Comment by harinarayanann** [comment]
I have updated and create a pull request. Thanks

**Comment by barteksekula** [comment]
Fixed in https://github.com/advanced-cms/advanced-reviews/pull/201
