### ISSUE TITLE
EPI Server Advanced.CMS.AdvancedReviews

### ISSUE THREAD

**Issue by YamitMoran** [advanced-cms/advanced-reviews#178]
When the editor adds the gadget for the external reviews, the script, that comes from the advanced cms package, returns in the response a 302 status code and a location redirect url, which is the login page for Episerver. 
When the CMS is accessed again, it completely crashes and the page stays blank, without any content, except for the admin panel at the top.

**Comment by barteksekula** [comment]
@YamitMoran does it work for you in the sample alloy? we would need some more info as this add-on works successfully for hundreds of clients.

**Comment by YamitMoran** [comment]
Thanks @barteksekula. This gadget works for some users and for others it doesn’t, which may lead to the conclusion, that this is a permission problem, stopping EpiServer from loading the script.
![SS](https://user-images.githubusercontent.com/75030906/100326984-52e0c800-2fd3-11eb-9a09-102a995c12fb.png)

**Comment by barteksekula** [comment]
Do you have web.config entries?
They should have been added by this nuget transform:
https://github.com/advanced-cms/advanced-reviews/blob/master/src/alloy/web.config.transform#L25

**Comment by YamitMoran** [comment]
Thanks, @barteksekula!
We compared the our Web.config file in the project with the source code, that you sent. 
Everything seems to be the same, except for one line, where a “rootPath” attribute is set in the “protectedModules” element (it’s in the screenshot). 
Do you know if this can be the cause of our problem?
![protectedModules](https://user-images.githubusercontent.com/75030906/100593897-a6b81d80-3301-11eb-9b45-1e6acf91ba99.PNG)

**Comment by barteksekula** [comment]
Can you give it a shot and change it?

**Comment by YamitMoran** [comment]
Hi @barteksekula ,
We tried and got he following error:
![2020-12-22_22-56-45](https://user-images.githubusercontent.com/75030906/102932456-004adc80-44a9-11eb-99a8-a680098a9370.jpg)
Could you please advise?
Thanks!

**Comment by barteksekula** [comment]
@YamitMoran that's not what I meant. Please follow the link from my previous comment.
Make sure you have the correct <location> nodes in web.config.
If you're saying that the issue is related to security then some users (who cannot access the scripts) might not be in correct roles.

**Comment by barteksekula** [comment]
And it's not about 'protectedmodules' but about <location>.
Please make sure that all correct users can access that javascript file that you have in your screenshot.

**Comment by YamitMoran** [comment]
Thank you, @barteksekula!
We will check again and update soon.

**Comment by barteksekula** [comment]
@YamitMoran any news?

**Comment by YamitMoran** [comment]
Yes! thank you @barteksekula it works great now.

**Comment by joemayberry** [comment]
@barteksekula The transform file you referenced above is not longer available. Do you still have a copy? I believe we are seeing the a similar issue.

**Comment by barteksekula** [comment]
@joemayberry master now contains .net5 code.
.net4 was moved here:
https://github.com/advanced-cms/advanced-reviews/blob/net4_master/src/alloy/web.config.transform

what's the issue?
In 0.9.1 I removed the need for custom group `ExternalReviewers`. You can control it yourself via web.config.
The idea is that VIEW links are public
The EDIT links are only accessible by people with an account

**Comment by joemayberry** [comment]
@barteksekula We are seeing a strange 403 error on the initializer.js file on the DXP for some users, but not on local dev environments. I just upgraded to 0.9.1, and pushing to integration now. Will see if that resolves the issue.

**Comment by joemayberry** [comment]
@barteksekula It looks like upgrading to 0.9.1 resolved the issue. Thank you for the support.

**Comment by barteksekula** [comment]
Great!
