### ISSUE TITLE
Multi-Language Editing

### ISSUE THREAD

**Issue by Halloweenh20** [advanced-cms/advanced-reviews#179]
We have a CMS in both French and English and we want to use Advanced-Reviews. The problem is... as it is right now, it does not seem to work. 

Here is how to duplicate the issue
0. Start with English
1. Create a project 
2, Edit a page (change the title) so it gets into the project
3. Add a block to the page - so it gets added to the project
4. Switch to French and do the same thing

The page in both French and English have the same Id
The block in both French and English have the same Id as well

Can you help or tell me what i'm doing wrong?

**Comment by barteksekula** [comment]
Released in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.8.1
