### ISSUE TITLE
Getting different result from contentloader in the external review context

### ISSUE THREAD

**Issue by mohsenhosseinalizadeh** [advanced-cms/advanced-reviews#182]
I faced this issue with the `ContentLoader.Get` method when we are in the External Review Context. Actually, the `Get` method of the ContentLoader returns different results when you call it twice in a row! Which is very strange.
I have tested it on the Alloy template on the repository with the latest version and I faced this issue when there is an ajax request.

Steps to reproduce:

1- Login to the admin section, select the Alloy Plan page, choose the All Properties mode and in the "Large content area" section, edit the "Customer testimonial wide teaser" block, do any simple change but do not publish it.

2- Return to the Alloy Plan page and via the External Review Links gadget generate a new review link.

3- At the end of the `index.cshtml` for the product page in this path (Views/ProductPage/index.cshtml) add the following codes. This code send a simple ajax request to the `ContactBlockController.cs` for testing.

```
@if (ExternalReview.IsInExternalReviewContext) {
    <script>
        fetch('/contactblock/fetch/?token=@ExternalReview.Token')
            .then(response => console.log(response));
    </script>
}
```
4- Add the following action method to the `ContactBlockController.cs`. Please note that we call the Get method twice in a row with the same content reference.
```
[Route("contactblock/fetch/{token}/")]
[HttpGet]
public ActionResult Fetch(string token)
{
    if (!string.IsNullOrEmpty(token))
        AdvancedExternalReviews.ExternalReview.Token = token;

    var block = _contentLoader.Get<TeaserBlock>(new ContentReference(46));
    var newblock = _contentLoader.Get<TeaserBlock>(new ContentReference(46));
    return null;
}
```
Please note that I use the static content reference id (46). Maybe you need to change it to the "Customer testimonial wide teaser" block ID.

Now if you debug this code by browsing the generated review link (step 2),  and watch the `block `and `newblock `variables, you can see that they have different `ContentLink` properties.

![image](https://user-images.githubusercontent.com/61750238/104571633-9bbc1100-5653-11eb-999d-0289be3c7c08.png)

Can please take a look at this strange issue!?

I found a possible fix for it. It seems that we need to use `LoadedContent` event instead of `LoadingContent` event. As I tested, it can fix this issue. 

In the `CustomContentLoaderInitialization.cs` at line 21, I changed the 
```
private void Events_LoadingContent(object sender, ContentEventArgs e)
```
to 
```
private void Events_LoadedContent(object sender, ContentEventArgs e)
```

At line 18, I changed the 
```
events.LoadingContent += Events_LoadingContent;
```
to 
```
events.LoadedContent+= Events_LoadingContent;
```
And at line 69, I changed 
```
events.LoadingContent -= Events_LoadingContent;
```
to 
```
events.LoadedContent -= Events_LoadingContent;
```

Thanks a lot for your consideration

**Comment by barteksekula** [comment]
Why do you need that Fetch in ContentBlockController?

**Comment by mohsenhosseinalizadeh** [comment]
@barteksekula It is a simple example to reproduce the issue. In my real project, I have an ajax request and I need to fetch data.

**Comment by barteksekula** [comment]
That's not supported unfortunately. You are not supposed to pass the token around.
For now token can only be used inside a single request, we don't support passing it around via xhr requests.
You would have to write the code yourself that gets the common drafts in the ajax call.
Also you would need to validate if the token is valid and not expired yourself (this is handled by us by default by partial routers)

**Comment by mohsenhosseinalizadeh** [comment]
Thanks a lot for your help @barteksekula . So should we close this ticket?

**Comment by barteksekula** [comment]
Do you know how to write that code?
Sure, you can close.

**Comment by mohsenhosseinalizadeh** [comment]
Yeah, I can cope with it!
