### ISSUE TITLE
PIN Codes triggering 500 error on Foundation site

### ISSUE THREAD

**Issue by daniel-isaacs** [advanced-cms/advanced-reviews#184]
When I log in via PIN code to an external review link on a foundation-mvc-cms, it triggers a 500 error.

Steps to reproduce on a foundation-mvc-cms site:
1. enable Pin Code security via initialization module
2. create an external review link, and set a PIN
3. open link in new incognito window (so I'm not authenticated)
4. enter PIN
 
Result: 
Correctly redirects to external review link -> 500 error triggered
I continue to get the 500 for any site URL until I delete the .AspNet.ApplicationCookie cookie that was created during the login.

Log attached.
[foundation-advanced-reviews-pin-code-error-log.txt](https://github.com/advanced-cms/advanced-reviews/files/5894359/foundation-advanced-reviews-pin-code-error-log.txt)

**Comment by daniel-isaacs** [comment]
To recreate in Alloy template:
Add _Html.AntiForgeryToken()_ to a page View and then create a review link with pin code, then browse to the page in an incognito window and enter the pin code.

**Comment by barteksekula** [comment]
@daniel-isaacs can't you skip the token validation for review links?

**Comment by barteksekula** [comment]
The PIN log in form is very simple. https://github.com/advanced-cms/advanced-reviews/blob/master/src/external-reviews/PinCodeSecurity/ExternalReviewLoginController.cs#L49 and I don't understand why the token is being validated. Any ideas?

**Comment by barteksekula** [comment]
@daniel-isaacs I managed to reproduce the issue when running Foundation site.
I think you need to tell the antiforgery validator which claim to use as the ID of the session.

Please add this to https://github.com/episerver/Foundation/blob/develop/src/Foundation/Global.asax.cs#L21
```cs
System.Web.Helpers.AntiForgeryConfig.UniqueClaimTypeIdentifier = System.IdentityModel.Claims.ClaimTypes.NameIdentifier;
```

After adding this line everything started to work.

**Comment by barteksekula** [comment]
@daniel-isaacs any news? Do you want me to contribute the fix to foundation or rather add this to our docs?
