### ISSUE TITLE
Share view links gives  a 400 

### ISSUE THREAD

**Issue by LennartEriksson** [advanced-cms/advanced-reviews#185]
I'm trying to share a review link - I get the dialog to fill out email address, but when I press send 
I get a 400 response

**Comment by barteksekula** [comment]
Stacktrace would be very helpful.

**Comment by barteksekula** [comment]
@LennartEriksson do you happen to have the stacktrace for the exception?

**Comment by LennartEriksson** [comment]
Managed to fix the issue - was a miss configuration in our code

**Comment by barteksekula** [comment]
OK thanks
