### ISSUE TITLE
External Editable View Issue

### ISSUE THREAD

**Issue by RhinonMike** [advanced-cms/advanced-reviews#186]
We're having issues getting the Editable View link working right.   The "View" link works fine and shows our draft content.  The content in the "Edit" view, where the reviewer can add pins/comments, shows the published content, not the draft content. Is this how it's supposed to work?  Permissions appear to be set up correctly as they have to log in and enter their reviewer name.

**Comment by barteksekula** [comment]
It's supposed to show the same unpublished content.
There's a sample Alloy in this repository where you can see how it works when properly configured.
Please take a look, maybe you can spot an issue in your configuration.

**Comment by barteksekula** [comment]
https://github.com/advanced-cms/advanced-reviews#development-if-you-would-like-to-help-in-development

**Comment by RhinonMike** [comment]
I'll try that, thanks!

**Comment by RhinonMike** [comment]
This looks to be a duplicate of #177.  Sorry!
