### ISSUE TITLE
ContentLoader.Get incorrect behavior in external review mode 

### ISSUE THREAD

**Issue by pavel-klevtsov** [advanced-cms/advanced-reviews#191]
Steps to reproduce.
1. Create a page and a block like this:
public class TestContentBlock : BlockData
{
public virtual string Title { get; set; }
}

and

public class TestContentPage : PageData
{
public virtual string Title { get; set; }

[AllowedTypes(typeof(TestContentBlock))]
public virtual ContentReference Reference { get; set; }
}

2. Create a view like this:

@model TestContentPage

@{
    var contentLoader = ServiceLocator.Current.GetInstance < IContentLoader > ();
    var block = contentLoader.Get < TestContentBlock > (Model.Reference);
}
@Model.Title

@block.Title

3. Create a block, set Title property. Publish block.
4. Create a page, set Title property, set Reference  property (use the block just created), publish the page
5. Create a new project
6. Change page's Title property and create a Ready to Publish version for the page (do not publish), do the same for for the block (change Title property and create Ready to Publish version)
7. Create an external review link using the project.
8. Open the page using the link
9. You will see that _@Model.Title_ contains the expected draft value, but _@block.Title_ always contain published value.
10. Update a view like this:

@model TestContentPage

@{
    var contentLoader = ServiceLocator.Current.GetInstance < IContentLoader > ();
    var block = contentLoader.Get < TestContentBlock > (Model.Reference);
    var block2 = contentLoader.Get < TestContentBlock > (Model.Reference);
}
@Model.Title

@block.Title

@block2.Title

11. Run the view using the same external review link. You will see that @block2.Title provides correct expected draft value. Only the first content request for the same content reference provides published version. The second call (thirh, fourth, ...) works correctly.

**Comment by pavel-klevtsov** [comment]
There is another, less obvious issue that happens because of ContentLoader.Get incorrect behavior in external review mode. It happens when we use ContentArea and ContentAreaItemExtensions.GetContent method.
Steps to reproduce.

1. Create a page and a block like this:
public class TestContentBlock : BlockData
{
public virtual string Title { get; set; }
}
and

public class TestContentPage : PageData
{
public virtual string Title { get; set; }

[AllowedTypes(typeof(TestContentBlock))]
public virtual ContentArea Area { get; set; }
}

2. Create a view like this:
@model TestContentPage

@Model.Title

@foreach (ContentAreaItem item in Model.Area.Items)
{
    var block = (TestContentBlock)item.GetContent();
    
    @block.Title
   
}

3. Create a block, set Title property. Publish block.
4. Create a page, set Title property, set Reference property (use the block just created), publish the page
5. Create a new project
6. Change page's Title property and create a Ready to Publish version for the page (do not publish), do the same for for the block (change Title property and create Ready to Publish version)
7. Create an external review link using the project.
8. Restart IIS.
8. Open the page using the link
9. You will see correct behavior (unpublished version)
10. Refresh the page immediately
11. You will see that @block.Title contains published version value (incorrect behavior)

It happens because ContentArea.Items property contains this code:
    public virtual IList<ContentAreaItem> Items
    {
      get
      {
        return this._contentAreaItems ?? (this._contentAreaItems = this.CreateContentAreaItemCollection());
      }
    //...

So when the first is first loaded, the method CreateContentAreaItemCollection() is called, which eventually calls for contentLoader.Get method for each item, so the  (TestContentBlock)item.GetContent() code calls for contentLoader.Get method a second time and provides correct data.
When we reload a page, the property _contentAreaItems is already initialized, so CreateContentAreaItemCollection() is called, so (TestContentBlock)item.GetContent() code calls for contentLoader.Get method a first time and provides incorrect data.

The ContentLoader.Get incorrect behavior was already mentioned in https://github.com/advanced-cms/advanced-reviews/issues/182 (there is a possible fix provided there)

**Comment by barteksekula** [comment]
Both issues were fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.8.5
