### ISSUE TITLE
Unable to view external review link

### ISSUE THREAD

**Issue by JamesOlano** [advanced-cms/advanced-reviews#203]
Hi, 

We installed the Advanced Reviews package from NuGet Package Manager on Visual studio to our solution. We tried to add an external review link while the changes on the page is not yet published. After opening the link, it now displays the error on the 2nd picture. The behavior is that “?preview_generated=True” is continuously appended on the URL.

![epi-1](https://user-images.githubusercontent.com/93336899/139289128-1d15ebcd-cbfd-4262-a29c-5eab68d6cb7b.jpg)
![site-1](https://user-images.githubusercontent.com/93336899/139289148-d52a4417-5c8d-41b9-b11e-d7b5aad9620a.jpg)
![site-2](https://user-images.githubusercontent.com/93336899/139289169-c8bcd174-d553-4ba8-b0fe-88b619355a95.jpg)

Are we missing out on something? Kindly help us on this issue we are encountering.

Thanks!

James

**Comment by JamesOlano** [comment]
> I assume you added a link having a project selected right? Does it work outside of project context?

We tried to moved it outside of project context and the external review link returned 404 page if the page is not yet published. For those published pages that have drafted changes, it does not display the updated changes.

**Comment by barteksekula** [comment]
This project is successfully used in numerous sites so there must be something specific to your site, some customization like custom UrlResolver or ContentAreaLoader or sth like that.
Could you try to reproduce in Alloy? It's very easy, just clone this repo and start the project.
Then you could try to add your customizations one by one to find which one is causing this.

**Comment by barteksekula** [comment]
@JamesOlano any updates?
