### ISSUE TITLE
Support for commerce product/category/variant pages? 

### ISSUE THREAD

**Issue by nolmsted** [advanced-cms/advanced-reviews#209]
Any plans to add in support for preview urls on commerce pages?

**Comment by barteksekula** [comment]
good idea, we haven't thought about it yet, but it sounds like a good candidate for the next feature

**Comment by barteksekula** [comment]
@nolmsted are you on .net core or .net framework?

**Comment by nolmsted** [comment]
Currently still on .net framework, but planning to migrate the project to .net 5 at some point this year. No problem if supported is only added for CMS 12+

**Comment by barteksekula** [comment]
Support added in https://nuget.optimizely.com/package/?id=Advanced.CMS.AdvancedReviews&v=1.3.0
