### ISSUE TITLE
External Review Page in incognito window not rendering blocks

### ISSUE THREAD

**Issue by RituM24** [advanced-cms/advanced-reviews#213]
Hi

We have a page with blocks and when we generate the external review link for it and view on the same browser where user is already logged in, it renders fine. However, if we copy and open this url in incognito window as anonymous user, the page loads with header, footer and basic text body, but no blocks render. The markup doesn't show anything and logs dont have any errors. We are on version 0.9.0 of the project.
We had an ExternalReviewes virtual role created and assigned it permissions to access certain locations in web.config. But i commented all those and it still didnt fix it.
Please advice on what may be the issue here.

**Comment by barteksekula** [comment]
Did you check the configuration from the Alloy added in this repository? Are you sure nothing is missing?

**Comment by barteksekula** [comment]
Just to make sure, you use VIEW or EDIT links? https://github.com/advanced-cms/advanced-reviews#external-review-component

**Comment by RituM24** [comment]
Hi
I use the external review url generated by the gadget. This has a GUID at the end. 
Also, could you please elaborate on the Alloy configuration you mentioned above?

**Comment by barteksekula** [comment]
Does it work for you if you install a fresh Alloy.
.net core - https://docs.developers.optimizely.com/content-cloud/v12.0.0-content-cloud/docs/installing-optimizely-net-5
.net framework - https://marketplace.visualstudio.com/items?itemName=EPiServer.EpiserverCMSVisualStudioExtension

**Comment by barteksekula** [comment]
Or you can also clone this repo, switch to net4 master and run the project.
The stuff you described is the most basic scenario, no special roles or anything should be needed. It is supposed to just work out of the box so there must be something special about your site that we need to find out.
custom content area loaders / custom renderers or any other custom code that changes the default episerver behaviour

**Comment by RituM24** [comment]
Hi
So we're still encountering this issue, but this time only on our int and prep environments. Local seems to be working with the same test user that's setup for int and prep too. The only difference i'm noticing here is that there are no additional image proxy get calls for when the blocks are not rendering. See screenshot : 
![image](https://user-images.githubusercontent.com/105823766/182249840-450e366a-6c24-4f21-8cd2-380865709768.png)

Please advice on what could be different in int and prep vs local, that its not working there. We made a deployment recently and restarted site and purged cache.. but no change.

**Comment by solita-kpetrov** [comment]
I also can confirm this issue in our project. For Optimizely 12 if a page has no access rights "Everyone" and an user is not authenticated, the page content is not visible by external review link. Seems Episerver code applies authorization requirement and prevents access to restricted content blocks.

**Comment by barteksekula** [comment]
are you able to reproduce the issue using the alloy from this project?
for .net framework:
https://github.com/advanced-cms/advanced-reviews/tree/net4_master#bug-reporting
https://github.com/advanced-cms/advanced-reviews/tree/net4_master#development-if-you-would-like-to-help-in-development

.net core:
https://github.com/advanced-cms/advanced-reviews/tree/master#bug-reporting
https://github.com/advanced-cms/advanced-reviews/tree/master#development-if-you-would-like-to-help-in-development

We would really appreciate a reproducible environment (a fork would be ideal) or at least details steps to reproduce. This add-on is installed on hundreds of public websites with different setups so it's hard for us to guess the cause of issues.

**Comment by solita-kpetrov** [comment]
for local .net core Alloy site (PIN code disabled):

1 New Page -> Landing Page
2 Add a block to 'Large content area', for example 'Teaser'
3 Update 'Visible to' for the page by unchecking 'Read' for 'Everyone'
4 Create external review link
5 Publish the page
6 The page by external review link requires login in incognito mode. 

If the page is available for 'Everyone' but blocks use personalized groups it's possible to see that the page is generally available by external link, but the content is hidden.

**Comment by barteksekula** [comment]
@solita-kpetrov Is the issue you described the same as in #218 ?

**Comment by solita-kpetrov** [comment]
@barteksekula Yes, looks the same. And we fixed it more or less the same way as in PR.

**Comment by barteksekula** [comment]
@solita-kpetrov solved in https://nuget.optimizely.com/package/?id=Advanced.CMS.AdvancedReviews&v=1.2.0
