### ISSUE TITLE
Error while sharing external link ("Share link to the content with external editor")

### ISSUE THREAD

**Issue by Anish-Peethambaran** [advanced-cms/advanced-reviews#215]
I am getting error while sharing link to the content with external editor. When I click on send button, I am getting 404 error. Attaching screen shot.
Advanced.CMS.AdvancedReviews 1.0.0

![image](https://user-images.githubusercontent.com/54981074/173120538-3b232362-301a-4b1f-b004-231b7fa4cd67.png)

**Comment by barteksekula** [comment]
Can you try in the Alloy attached to this repository? Everything is set up there. Maybe something is missing in your site?

**Comment by barteksekula** [comment]
You are right. There was a problem with routing. Will be fixed in 1.1.2

**Comment by barteksekula** [comment]
https://nuget.optimizely.com/package/?id=Advanced.CMS.AdvancedReviews&v=1.1.2
