### ISSUE TITLE
"Not found" error during using external review links

### ISSUE THREAD

**Issue by cezaryzysk** [advanced-cms/advanced-reviews#217]
Hey, 
I am getting 404 errors on loading the Edit and View pages from External Review Links. I noticed that the problem occurs if the content has not been published yet, after publishing the page is worked normally. The rest of the features are working fine.
I tested this add-on in another application, and everything was okay.
We are using advanced-reviews v0.9.1 and Episerver v11.20.12.
I've seen a very similar topic(https://github.com/advanced-cms/advanced-reviews/issues/53) before, but I haven't found a solution for myself here.
Could anyone help me in this regard?
Thanks in advance!
![image](https://user-images.githubusercontent.com/86838418/187362176-3dbbdbbb-39f8-4e01-abe9-029e14b4d228.png)
![image](https://user-images.githubusercontent.com/86838418/187365421-e4db4178-1acb-4328-8fc3-fd371693200e.png)

**Comment by barteksekula** [comment]
You do have the <location> nodes in web.config right?

**Comment by barteksekula** [comment]
@cezaryzysk could you please try the alloy from this repository?
> clone
> checkout net4_master
> setup.cmd
> site.cmd

Please note that .net framework is still using an old version of nodejs (https://github.com/advanced-cms/advanced-reviews/tree/net4_master#requirements)

**Comment by cezaryzysk** [comment]
Hey @barteksekula sorry for the delay,
In this test project everything looks fine: 
![image](https://user-images.githubusercontent.com/86838418/188869210-6521f024-ff38-4b9c-a4c9-7d5d9ac6b03d.png)
But I tested this plugin also for another project with .net framework and everything worked fine. The problem is only in this one project, do you have any idea what it could be?
