### ISSUE TITLE
"Restricted pages" requires login to see external content view url

### ISSUE THREAD

**Issue by nguyenminhvuong** [advanced-cms/advanced-reviews#218]
**Steps to reproduce:**

1. In Alloy site, create a container page which is NOT public (visible to Admin or Editor only)
2. Create another page is a child of container page in step 1
3. Create a **view** link in "External review links" section
4. Copy the generated link and open it in incognito mode
5. Browser redirects to login page

![image](https://user-images.githubusercontent.com/14576574/188804326-a1821ff6-3679-45ab-84f5-4cde808f0ae8.png)
![image](https://user-images.githubusercontent.com/14576574/188804384-1425a9ac-9bfc-46d2-81f0-4c65e6983aba.png)
![image](https://user-images.githubusercontent.com/14576574/188804535-e09200b9-6925-4a81-a380-07dc8803e019.png)

**Expected result:**

User can view the page without login

**Actual result:**

User need to login to view the page. This issue is not occurred in .NET framework version

**Comment by nguyenminhvuong** [comment]
@barteksekula: How long will this bug be fixed? Or can you tell me a solution, I will try to do it. Sorry for disturb, my customer is asking about the progress

**Comment by barteksekula** [comment]
@nguyenminhvuong hopefully soon, I've just created a PR.

**Comment by barteksekula** [comment]
Fixed in https://nuget.optimizely.com/package/?id=Advanced.CMS.AdvancedReviews&v=1.2.0
