### ISSUE TITLE
Multi-language site rendering primary site Mega Nav links in external review 

### ISSUE THREAD

**Issue by Uvarsni** [advanced-cms/advanced-reviews#227]
HI,

We are having a multi-language site and when trying to review the secondary language page in external review links gadget, it is rendering the Mega Navigation (Top Right) links of the primary language site.

Kindly advise how to overcome this issue?

**Comment by Uvarsni** [comment]
Hi Team,

Please advise on above query

**Comment by barteksekula** [comment]
Please share more info. 

. .net core or .net framework?
- version of advanced-reviews
- how do you render the problematic part?
