### ISSUE TITLE
Null reference exception while fallback to master language

### ISSUE THREAD

**Issue by solita-kpetrov** [advanced-cms/advanced-reviews#234]
Hi!

https://github.com/advanced-cms/advanced-reviews/commit/5600cdce6535bdcc6d443cab0177ac0b719d8add
in these changes 
var contentRouteData = _defaultUrlResolver.Route(urlBuilder, routeArguments); seems returns null in some cases (at least we are having this issue in last update) 
Shouldn't be there an additional null check?

We are not able to apply this update that contains an urgent fix https://github.com/advanced-cms/advanced-reviews/commit/b14ceb3fca0c1de268bdd55212798b3408002446

**Comment by barteksekula** [comment]
Of course, you are right.

**Comment by barteksekula** [comment]
[1.3.5](https://nuget.optimizely.com/package/?id=Advanced.CMS.AdvancedReviews&v=1.3.5) will be available soon
