### ISSUE TITLE
This doesn't seem to work with headless

### ISSUE THREAD

**Issue by landg-lance** [advanced-cms/advanced-reviews#236]
Are there any instructions on getting this plugin to work with headless v12 EPiServer?  I just tried installing it into our project, and none of the functionality is working for us.

**Comment by barteksekula** [comment]
What is the expectation when it comes to headless? This addon allows users to preview html of unpublished content items.

**Comment by landg-lance** [comment]
Headless requires an API endpoint.  Does this plugin extend the Content Delivery API in some way to view unpublished content?  Or maybe has it's own endpoint?  A link such as https://test.reviews.com/externalContentView/20a05637-ded8-4831-97dc-5989e910379d won't work with headless because the Front End website is delivered by another application, NOT by EPiServer.  eg our FE is an Angular app that is fed data via the Content Delivery API in EPiServer.

**Comment by barteksekula** [comment]
Unfortunately we do not plan to support this.
