### ISSUE TITLE
Generated image url is invalid

### ISSUE THREAD

**Issue by KongKvistad** [advanced-cms/advanced-reviews#240]
When creating an external review link,  every image on said page will generate a link through imageProxy, E.G:

`https://localhost:44390/ImageProxy?token=d099f130-79ad-4343-ad72-346d5dcd1b1a&contentLink=90443_878742?transform=DownFit&width=700&hash=ab0e358e1d29067d8539a4841c61ab17`

Removing the portion after the last question mark provides a valid link,
so maybe there is an issue with concatenating two question marks?

**Comment by barteksekula** [comment]
@KongKvistad who adds the second question mark?
This is the image proxy generator: https://github.com/advanced-cms/advanced-reviews/blob/master/src/Advanced.CMS.ExternalReviews/ExternalReviewUrlGenerator.cs#L23
