### ISSUE TITLE
Simultaneous Publishing of Entire Pages with Components & Enhancement to Share Links with Multiple Reviewers

### ISSUE THREAD

**Issue by ShaikhFarhin** [advanced-cms/advanced-reviews#245]
I am using Add-On Review for CMS 11. Is it possible to implement a feature that allows the simultaneous publishing of entire pages, including newly added blocks and media items, in one go after incorporating review feedback? Currently, when I revise a page that contains new blocks and media, only the page itself gets published, leaving the new components in draft status. It would be beneficial to have an option to publish the entire page with all associated content components at once.

Also, Currently, the option to share links with reviewers only allows for one email address at a time. It would be beneficial to enhance this feature so that multiple reviewers can be selected and added in one go, using comma or semicolon-separated email addresses. This would streamline the review process by enabling efficient sharing of content links with multiple stakeholders simultaneously.

**Comment by barteksekula** [comment]
This feature is not on our radar. This is just for review, we do not plan to touch the publishing workflow at all.
