### ISSUE TITLE
Question: Possible to change the edit url? 

### ISSUE THREAD

**Issue by MiaHolmberg** [advanced-cms/advanced-reviews#251]
Is it possible to change the url path for the edit link? 

We dont want to include the editui path in the url. When testing it today the url looks like this:
https://localhost:57613/editui/advanced-cms-external-reviews/PageEdit/Index/00439471-63c2-5ebd-9bb5-662e7841e400

we would like to have it more like this:
https://localhost:57613/external-review/PageEdit/Index/00439471-63c2-5ebd-9bb5-662e7841e400

Thanks for a great plugin!

**Comment by barteksekula** [comment]
@MiaHolmberg It's not possible at the moment. Only the VIEW tokens have this kind of url.
EDIT tokens are only accessible to logged in users which is why the /editui/advanced-cms-external-reviews is needed
We did it to get controller registration with correct authorization policy for free
