### ISSUE TITLE
Build script doesn't seem working locally

### ISSUE THREAD

**Issue by javafun** [advanced-cms/advanced-reviews#41]
I followed the README instruction to build the solution locally and received the following errors

![image](https://user-images.githubusercontent.com/332991/59316018-b4d64080-8cff-11e9-9ade-97d12adcb333.png)

**Comment by barteksekula** [comment]
They seem to have unpublished ts-loader@5.4.6
https://github.com/TypeStrong/ts-loader/issues/929

We will update it today.
