### ISSUE TITLE
Language is part of urls generated - even for non globalized site

### ISSUE THREAD

**Issue by AThraen** [advanced-cms/advanced-reviews#47]
I get urls like this: https://localhost:44381/en/externalContentView/9a29f47a-026e-4fe6-86db-8437d2592d4e but my site is not globalized and does not use '/en/'.

**Comment by karorapepper** [comment]
Just a workaround (if it helps anyone) until next release, is to add a redirect (using Redirect Manager on Dashboard) to redirect any /en/externalContentView/ to /externalContentView/

**Comment by barteksekula** [comment]
@karorapepper Thanks a lot of your comment.
We are about to release a new milestone 0.2.0 that will fix that issue.
