### ISSUE TITLE
404 error on using editable link

### ISSUE THREAD

**Issue by karorapepper** [advanced-cms/advanced-reviews#53]
Hi, 

Thanks for creating this very useful addon.
However I am getting 404 error on loading the Editable External Review link. I am able to use rest of the features fine. The view only link works well too (although it adds an additional /en before /externalContentView resulting in 404 as well but was able to get around that by adding redirect to remove /en) but edit link keeps giving 404 error. Can anyone help in this regard?
I have already added the ExternalReviewInitialization file and set EdiatbleLinksEnabled option to true.
Another question what is the use of following 3 ExternalReviewOptions:
 public string ReviewsUrl { get; set; }
        public string ContentPreviewUrl { get; set; }
        public string ContentIframeEditUrlSegment { get; set; }

Thanks.
![ExternalReview 404 Error](https://user-images.githubusercontent.com/43224090/60483681-dc567280-9cd9-11e9-8494-752f45fae124.JPG)
![ExternalReviewInitialization Code](https://user-images.githubusercontent.com/43224090/60483682-dc567280-9cd9-11e9-912c-57f5bf1f48c5.JPG)

**Comment by karorapepper** [comment]
Hi @barteksekula The 404 issue I am getting is not same as globalisation Url issue due to language fragment. In my case even after removing the language fragment the (Created as Edit) editable external reviewer urls are returning 404 error while View only external reviewer urls are working fine. Is this something you have already fixed? Please read more details in comment above. Thanks!

**Comment by barteksekula** [comment]
@karorapepper I've just checked once again to be sure but everything seems to work just fine.
an example url for an external reviewer is as follows (never contains the language branch):
http://example.com/externalContentReviews/da996ac1-418e-4a0a-990a-e03d85cd72a1
however urls for "view" are like this (this one has the language branch):
http://example.com/en/externalPageReview/da996ac1-418e-4a0a-990a-e03d85cd72a1

Could you please share more details? What user are you trying to log on after opening 'externalContentReviews/' path? 
It seems we did not describe it in the documentation but it's only the ExternalReviewers group members that are allowed to access that path (defined in web.config)

**Comment by barteksekula** [comment]
@karorapepper did this work for you?

**Comment by karorapepper** [comment]
hey @barteksekula, nope the issue not resolved yet, the editable reviewer link still gives 404. I assumed it may have something to do with permissions setup for content editor user roles which is not allowing to create pages in editable mode. However my content editor/reviewers only needed viewable links hence didn't pursue for the solution. Though would be good to find a solution.

**Comment by karorapepper** [comment]
Also @barteksekula from your previous comment I think you are mixing two different issues I was talking about - 
1. which you already fixed in later version, was the language branch code (en etc) was getting appended to url. I managed to fix this by using redirects until we had the version fix. So this is not a problem.
2. The problem was only with pages for which content editors created preview in "edit" mode. Those when logged in with "ExternalReviewers" or any role always gave 404. As if the page never got created when clicked on Edit button using plugin only a url is generated with new guid each time but no page to view.

**Comment by barteksekula** [comment]
Fixed in: https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.3.1

**Comment by barteksekula** [comment]
@karorapepper does it work for you now?

**Comment by leonardofraga91** [comment]
Hi, @barteksekula I'm facing the same problem above. I have implemented the class that enables editable links.

![image](https://user-images.githubusercontent.com/87445035/128897703-592c27a2-7363-4942-a9b7-aae38668e61a.png)

For all view links everything works fine. But when I try to create an 'Edit' link I always get the not found code.

Looking at the Browser's Network tab I found an URL that not seems mentioned anywhere. (.../externalpagereview/...)
![image](https://user-images.githubusercontent.com/87445035/128898142-2dba2697-657b-4ce4-9d24-19e3d98e9820.png)

Can be this the problem?

> Also @barteksekula from your previous comment I think you are mixing two different issues I was talking about -
> 
> 1. which you already fixed in later version, was the language branch code (en etc) was getting appended to url. I managed to fix this by using redirects until we had the version fix. So this is not a problem.
> 2. **The problem was only with pages for which content editors created preview in "edit" mode. Those when logged in with "ExternalReviewers" or any role always gave 404. As if the page never got created when clicked on Edit button using plugin only a url is generated with new guid each time but no page to view.**

It seems exactly with the second case mentioned by `karorapepper `.

Informations:
Advanced.CMS.AdvancedReviews = 0.9.0
EpiServer.CMS.Core = 11.20.3 - _Dependency_
EpiServer.CMS.UI = 11.32.0 - _Dependency_

Can you give me some help with that?
