### ISSUE TITLE
Login loop, being able to review login page

### ISSUE THREAD

**Issue by dlwniels** [advanced-cms/advanced-reviews#71]
For some reason I keep seeing the log in page, I log in with valid credentials and see the log-in page again. The plug-in thinks I'm viewing the actual content I requested and allows me to place pins on the log-in page itself.

Url: http://localhost:1812/Util/login.aspx?ReturnUrl=%2fexternalContentReviews%2f6c9d1268-4417-4549-b5cd-60cee9659784
![image](https://user-images.githubusercontent.com/47145826/63030021-e8754880-beb1-11e9-9e01-b8faca4b322e.png)

Url: http://localhost:1812/externalContentReviews/6c9d1268-4417-4549-b5cd-60cee9659784
![image](https://user-images.githubusercontent.com/47145826/63030036-ed39fc80-beb1-11e9-94e0-f5d3f419fa47.png)

Url: http://localhost:1812/externalContentReviews/6c9d1268-4417-4549-b5cd-60cee9659784
![image](https://user-images.githubusercontent.com/47145826/63030089-0b9ff800-beb2-11e9-80fb-eb202dfba15a.png)

**Comment by barteksekula** [comment]
Just making sure.. is `Reviewer` a member of `ExternalReviewers` group?
https://github.com/advanced-cms/advanced-reviews#security

**Comment by dlwniels** [comment]
For some reason it fixed itself after a couple days. I didn't change anything. When I had the problem I cleared my cookies and cache several times, I also restarted the webbrowser.

Yes, my user was part of "ExternalReviewers". The account also never was disabled because of too many failed login attempts. 

I believe this is an episerver bug and not related to your package. I'll close it.

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.3.1

**Comment by barteksekula** [comment]
@dlwniels does it work for you now?

**Comment by dlwniels** [comment]
@barteksekula I haven't had the problem since the update, so I would say it's solved. It was something that rarely happened, so could've been that I am just lucky. If I ever have it again, I will log it.

Thanks!
