### ISSUE TITLE
Comment layout issue with EPiServer.Cms.UI version 11.22

### ISSUE THREAD

**Issue by hahuynhniteco** [advanced-cms/advanced-reviews#77]
Hi @barteksekula 
Can you please help a check for comment UI of advanced reviews, it looks not good with EPiServer.Cms.UI version 11.22. It looks good with earlier UI version 11.21

![image](https://user-images.githubusercontent.com/44801946/67451814-a0aa3480-f64b-11e9-8e57-8fe90c178ec6.png)

Thanks,
Ha

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.4.0

**Comment by barteksekula** [comment]
Thanks for reporting @hahuynhniteco
