### ISSUE TITLE
Incorrect links on newly created project pages set to Ready for Publish - External Reivew

### ISSUE THREAD

**Issue by eckleyval** [advanced-cms/advanced-reviews#87]
The Project review is working great for edits to previously published pages within a projects.  All the edits are showing up fine.  

However when I add a new page to a project (set to Ready for Publish) and  create a link to this page, It is showing an incorrect link when testing.   If I publish the page then the link works fine.

The Individual external links to the pages set to "ready for publish" are working, it is just the links via the project that which I'm seeing this.  It could possibly be something which isn't set up on my end.

**Comment by barteksekula** [comment]
@eckleyval so you would expect that the link to that newly added page would be to project-related version or not-project-related version?
While in project mode then all created tokens contain projectId that will be injected when trying to view such a link.

**Comment by barteksekula** [comment]
@eckleyval any comments?

**Comment by eckleyval** [comment]
Yeah - I would expect it to be project related, so that we can migrate through new pages across an entire project -   Sorry for the late reply...

**Comment by barteksekula** [comment]
I tried to reproduce this today and it worked fine for me.
Would it be possible for you to create a bit more details "Steps to reproduce" ?

**Comment by barteksekula** [comment]
No response
