### ISSUE TITLE
External review is not working properly if data of the block get from the page's properties.

### ISSUE THREAD

**Issue by gt-se** [advanced-cms/advanced-reviews#90]
Hi,

I would like to report an issue with this addon.

Test data: a page contains a block, and several properties (these properties have data). The block is designed to display the data stored in the page's properties. 

Issue: when sharing this page via the external review link function, this block doesn't display any data, because it cannot resolve the current page.

Refer attached screenshot below.
![chrome_bbhLTwXVdP](https://user-images.githubusercontent.com/58317822/71612328-49d45480-2bd2-11ea-9185-2d2432f8b032.png)

- Expect: the email address should be displayed next to the mail icon.

Our temporally solution for this issue is using IPageRouteHelper to fetch the properties' data of the page to the attached block.

Note: this block is displaying data properly on the On-page Editing mode.

Thanks,
Harvey

**Comment by barteksekula** [comment]
@gt-se what is the generated url? are you on the latest version? I did some improvements about that particular issue in https://github.com/advanced-cms/advanced-reviews/commit/a8780fc67692fbb7251685f861e8f82db141c9ca

However, I was not able to solve an issue with pages that were never published before. Is that what you see yourself? Does it work for pages that were published before and does not work only for pages that were never published?

**Comment by gt-se** [comment]
Hi @barteksekula,

Please find the answer below:

Point 1: below is the generated URL. But bear in mind this is a local link so you cannot access it.
https://local.grantthornton.ca/externalContentReviews/f241bfcc-86b1-4caa-9345-9839b0e61866

Point 2: we used the latest version which is 0.5.1.

Point 3: your improvement was fixed for other issues, not the one we reported. We had pulled this request and tested it.

Point 4: about never unpublished page issue, both published and never published have same output.

Point 5: currentPage code:
`var pageRouteHelper = EPiServer.ServiceLocation.ServiceLocator.Current.GetInstance<IPageRouteHelper>();
var currentPage = pageRouteHelper.Page;`

Hope this helps.

Regards,
Harvey

**Comment by barteksekula** [comment]
@gt-se would it be possible for you to create a fork with reproducible scenario? that would help a lot and speed things up

**Comment by barteksekula** [comment]
@gt-se any comments here? maybe at least you can share the code from template?

**Comment by gregwiechec** [comment]
should be fixed in #111

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.5.3
