### ISSUE TITLE
Turn off Review mode: page cannot scroll

### ISSUE THREAD

**Issue by gt-se** [advanced-cms/advanced-reviews#91]
1. Open external review link
2. Turn off review mode (on right panel)
Actual result: after turn off review mode, the page cannot scroll down
Refer attached clip!
[addon-issue.zip](https://github.com/advanced-cms/advanced-reviews/files/4018216/addon-issue.zip)

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.5.2
