### ISSUE TITLE
Addon is not displaying if using image and link (URL property)

### ISSUE THREAD

**Issue by gt-se** [advanced-cms/advanced-reviews#92]
Hi,

There's another issue with this addon. It is not working with URL property.
![chrome_wxxl8IiIG1](https://user-images.githubusercontent.com/58317822/71863423-64a54c80-312f-11ea-9096-1c4f4a1fbbf1.png)

![chrome_N3kLIWcIh7](https://user-images.githubusercontent.com/58317822/71863349-30319080-312f-11ea-8dc1-5d7088b99583.png)
Reproduce step:
Include URL property to a page type:
` [CultureSpecific]
        [Display(Name = "Main content area", GroupName = SystemTabNames.Content, Order = 200)]
        public virtual ContentArea MainContentArea { get; set; }`

Thanks,
Harvey

**Comment by barteksekula** [comment]
@gt-se could you please share both model property and how it's rendered in the view? (I assume it was a typo that you posted a ContentArea above right?)

**Comment by barteksekula** [comment]
@gt-se 
I've just tried to reproduce the issue and it worked fine for me.

Model:
`
[Display(Name = "Image", Order = 100)]
public virtual Url Image { get; set; }
`

View:
`
<img src="@Url.ContentUrl(Model.CurrentPage.Image)" />
`

The image is correctly displayed in both VIEW and EDIT scenarios.
Please reopen the issue if it still does not work for you.
