### ISSUE TITLE
So many bugs - this addon breaks the CMS for editor role with IE11

### ISSUE THREAD

**Issue by gt-se** [advanced-cms/advanced-reviews#95]
Reproduce step:

1. User with editor role only
2. Using Internet Explorer 11

![iexplore_aF7H0uT3rH](https://user-images.githubusercontent.com/58317822/72773166-dbb30880-3c38-11ea-863b-4277bd36022b.png)

**Comment by barteksekula** [comment]
@gt-se this is an open source add-on that we do in our free time. we haven't actually thought if we need to still support ie11. 
is IE11 a must for you?

**Comment by gt-se** [comment]
@barteksekula : yes, IE11 still widely be used in many firms as default web browser.
Thanks!

**Comment by barteksekula** [comment]
It was a conscious decision for us to drop support of IE11 which is 11 years old now. Of course the Core EPiServer still has IE11 support but this is a personal add-on and you are actually the first one to mention IE11 in half a year.
We will try to estimate how much time would it be to downgrade but it's hard to predict when it could happen.

Maybe you would like to give it a shot? I assume it's just a matter of downgrading mobx to 4.x.x as mobx5 is ES6 only.

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.5.2
