### ISSUE TITLE
PIN position is not working properly

### ISSUE THREAD

**Issue by gt-se** [advanced-cms/advanced-reviews#96]
The comment PIN position is unstable.
PIN location in the internal:
![internal-review](https://user-images.githubusercontent.com/58317822/72773519-f46fee00-3c39-11ea-9a2e-200dd2d91f7f.png)

PIN location in the external
![external-review](https://user-images.githubusercontent.com/58317822/72773523-f89c0b80-3c39-11ea-9c61-08e9a5e4fcfb.png)

**Comment by barteksekula** [comment]
@gt-se what does it mean "in the internal" or "in the external"?

**Comment by barteksekula** [comment]
@gt-se is the pin added on top of an episerver property (element rendered by Html.PropertyFor helper?
or an element with Html.EditAttributes?
Is the resolution and the window size the same on both internal and external?
do you have some kind of responsive design on your page?

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.5.2
