### ISSUE TITLE
Add possibility to disable add-on

### ISSUE THREAD

**Issue by TNMH** [advanced-cms/advanced-reviews#97]
Hi!
We would like to use this add-on in a production environment. For debugging and security reasons it would be nice to have an option to disable this plugin.

Thank you for considering this request.

**Comment by barteksekula** [comment]
@TNMH would you expect a toggle in admin mode? web.config or rather an option in the c# config api?

**Comment by TNMH** [comment]
@barteksekula An option in the C# config API would be our preferred method.
Thank you very much for your work.

**Comment by barteksekula** [comment]
Added in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.5.2
